x-service-templates:
  app: &app
    image: gaoliveira21/rinha2025:0.1
    environment:
      - PORT=8080
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor:8081
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=rinha_payments
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.375"
          memory: "85M"

services:
  nginx:
    image: nginx:1.29-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app01
      - app02
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"
  db:
    image: postgres:17-alpine
    networks:
      - backend
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha_payments
    deploy:
      resources:
        limits:
          cpus: "0.60"
          memory: "165MB"
  app01:
    <<: *app
    container_name: rinha2025-app-01
    hostname: app01
    depends_on:
      - db
  app02:
    <<: *app
    container_name: rinha2025-app-02
    hostname: app02
    depends_on:
      - db

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
